site_name: Scala Basic

nav:
  - はじめに: index.md
  - 環境構築:
    - インストール: setup/install.md
    - IDE: setup/ide.md
    - プロジェクトの作成: setup/new-project.md
    - プロジェクトの読み込み: setup/import-project.md
    - Scalaワークシート: setup/worksheet.md
  - 基本:
    - 文字の出力: basic/output.md
    - コメント: basic/comment.md
    - 文字列と数値: basic/string-and-int.md
    - 変数: basic/variable.md
    - 比較演算: basic/compare.md
    - 条件分岐(if): basic/branching.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
